runtime: nodejs20
env: standard

handlers:
  - url: /emubench\.svg
    static_files: dist/emubench.svg
    upload: dist/emubench\.svg

  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/(.*)

  - url: /(.*\.(json|ico|png|jpg|jpeg|gif|webp|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|png|jpg|jpeg|gif|webp|woff|woff2|ttf|eot)$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
